package com.rivnoj.javacore.exception.runtime.test;

public class RuntimeExceptionTest1 {
  //@SuppressWarnings("null")
  public static void main(String[] args) {
    // Object object = null;
    // System.out.println(object.toString());

    int[] nums = {1, 2};
    System.out.println(nums[2]);
  }
}
